name: go-encryptor
base: core24
version: "2.1.0"
summary: A simple file encryptor
description: |
  go-encryptor is created to be as simple as possible to help you
  encrypt and decrypt files.

grade: stable
confinement: strict

apps:
  go-encryptor:
    command: bin/go-encryptor
    plugs:
      - home
      - removable-media

parts:
  go-encryptor:
    plugin: go
    source: .
    build-snaps:
      - go/latest/stable
