name: release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GOOS: darwin
            GOARCH: amd64
            suffix: darwin-amd64
          - GOOS: darwin
            GOARCH: arm64
            suffix: darwin-arm64
          - GOOS: windows
            GOARCH: amd64
            suffix: windows-amd64.exe
          - GOOS: linux
            GOARCH: amd64
            suffix: linux-amd64
          - GOOS: linux
            GOARCH: arm64
            suffix: linux-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Build ${{ matrix.suffix }}
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: |
          mkdir -p ./artifacts
          go version
          go build \
            -ldflags="-X 'github.com/mrinjamul/cipherix/utils.Version=${GITHUB_REF_NAME}'" \
            -o "./artifacts/cipherix-${GITHUB_REF_NAME}-${{ matrix.suffix }}"
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.suffix }}
          path: ./artifacts

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        name: Download artifacts
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: ./artifacts
      - name: Generate checksums
        run: |
          cd ./artifacts
          sha256sum * > SHA256SUMS
          cat SHA256SUMS
      - name: Publish artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
